import type { Metadata } from "next";
import { Cormorant_Garamond, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

// 1. Configure the Google Font
const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify the weights you need
  display: "swap",
  variable: "--font-cormorant", // This is the modern way using CSS variables
});

// 2. Configure the Local Fonts
const mostera = localFont({
  src: "../fonts/mostera.ttf", // Adjust path if needed
  display: "swap",
  variable: "--font-mostera",
});

const monas = localFont({
  src: "../fonts/monas.ttf", // Adjust path if needed
  display: "swap",
  variable: "--font-monas",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tarot Jojo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cormorant.variable} ${mostera.variable} ${monas.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
